# Generated by Django 4.2.7 on 2023-11-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceMaster",
            fields=[
                (
                    "invoice_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("invoice_date", models.DateField()),
                ("container_num", models.CharField(max_length=20)),
                ("port_dest", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name="Invoice",
            new_name="UploadInvoice",
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("unit_value", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "invoice_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_import.invoicemaster",
                    ),
                ),
            ],
        ),
    ]
