# Generated by Django 4.2.7 on 2023-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0002_invoicemaster_rename_invoice_uploadinvoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_value",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
