# Generated by Django 4.2.7 on 2023-11-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0003_alter_invoiceitem_unit_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProFormaMaster",
            fields=[
                (
                    "pi_ref",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("other_ref", models.CharField(max_length=10)),
                ("port_dest", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ProFormaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("ncm", models.CharField(max_length=20)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_value", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "pi_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_import.proformamaster",
                    ),
                ),
            ],
        ),
    ]
