# Generated by Django 4.2.7 on 2023-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0004_proformamaster_proformaitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformamaster",
            name="proforma_date",
            field=models.DateField(default="2023-10-23"),
            preserve_default=False,
        ),
    ]
