# Generated by Django 4.2.7 on 2023-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0005_proformamaster_proforma_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="num_item",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proformaitem",
            name="num_item",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
