# Generated by Django 4.2.7 on 2023-12-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0006_invoiceitem_num_item_proformaitem_num_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=20)),
                ("invoice_date", models.DateField()),
                ("container_num", models.CharField(max_length=20)),
                ("port_dest", models.CharField(max_length=20)),
                ("num_item", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("unit_value", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.IntegerField()),
                (
                    "invoice_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_import.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProForma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pi_ref", models.CharField(max_length=20)),
                ("other_ref", models.CharField(max_length=10)),
                ("proforma_date", models.DateField()),
                ("port_dest", models.CharField(max_length=20)),
                ("num_item", models.IntegerField()),
                ("brand", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("ncm", models.CharField(max_length=20)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_value", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=30)),
                ("user_last", models.CharField(max_length=30)),
                ("user_email", models.CharField(max_length=30)),
                ("user_phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="proformaitem",
            name="pi_ref",
        ),
        migrations.DeleteModel(
            name="InvoiceItem",
        ),
        migrations.DeleteModel(
            name="InvoiceMaster",
        ),
        migrations.DeleteModel(
            name="ProFormaItem",
        ),
        migrations.DeleteModel(
            name="ProFormaMaster",
        ),
        migrations.AddField(
            model_name="ledger",
            name="proforma_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_import.proforma"
            ),
        ),
    ]
