# Generated by Django 4.2.7 on 2023-12-01 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0007_invoice_ledger_proforma_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
