# Generated by Django 4.2.7 on 2023-12-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0008_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="description",
            field=models.CharField(default="xxx", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ledger",
            name="invoice_date",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ledger",
            name="invoice_ref",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ledger",
            name="proforma_date",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ledger",
            name="proforma_ref",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ledger",
            name="invoice_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="proforma_id",
            field=models.IntegerField(),
        ),
    ]
