# Generated by Django 4.2.7 on 2023-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0009_ledger_description_ledger_invoice_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pl_unit_weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
