# Generated by Django 4.2.7 on 2023-12-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0010_invoice_pl_unit_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillLading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=20)),
                ("port", models.CharField(max_length=20)),
                ("freight", models.DecimalField(decimal_places=0, max_digits=5)),
                ("quantity", models.IntegerField()),
                ("container", models.CharField(max_length=20)),
                ("weight", models.FloatField()),
            ],
        ),
    ]
