# Generated by Django 4.2.7 on 2023-12-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0012_billlading_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="billlading",
            name="gross_weight",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="billlading",
            name="net_weight",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
