# Generated by Django 4.2.7 on 2023-12-10 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_import", "0013_billlading_gross_weight_billlading_net_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billlading",
            name="weight",
        ),
    ]
